language: bash
services: docker

before_install:
- echo "$DOCKER_LOGIN" | docker login -u "$DOCKER_PASSWORD" --password-stdin # Set these as environment variables
- travis_wait 50 docker build -t android-build-box .

script:
- docker run -it --rm android-build-box sdkmanager --version

after_script:
- docker images

deploy:
  provider: script
  script: sudo docker push $HUB_NAME:$TRAVIS_TAG # Set HUB_NAME as environment variables
  on:
    tags: true
    branch: master
